### ISSUE TITLE
extending torchdash

### ISSUE THREAD

**Issue by saikrishnarallabandi** [CleanPegasus/TensorDash#14]
I am looking to extend torchdash to include logging some custom variables. For example, I am trying to include coarse loss and fine loss (both in training and validation). What is the best way to accomplish this?

I am currently looking to add a new file alongside *dash.py. Do you suggest its better to extend within the file torchdash?

**Comment by CleanPegasus** [comment]
Hi! Thanks for your suggestion. We will add an option to include custom metrics in the next version.

**Comment by saikrishnarallabandi** [comment]
Also noticed that the logging stops after a while. even though the model is still training. any hints as to why this could happen? i have replicated this behavior on mutliples models, running from multiple servers. typically deep learning models train for a larger period of time, so it will be great to resolve this.

**Comment by harshitm98** [comment]
Hey Sai Krishna! Can you check if the data is updated in the app, by dragging down to refresh? One possible reason might be that data is being uploaded by the model but is not displaying since the app does not automatically sync. We are currently working on this specific issue and it would be fixed in the next release.

**Comment by saikrishnarallabandi** [comment]
thanks for the prompt response. Yes. I have tried refreshing, killing the app completely and restarting as well. Here is an observation that might help: I ran two models concurrently, one that runs 40 epochs per hour and another that runs 200 per hour. The first model seems to stop updating after 30 epochs, and the latter after 160 epochs.

**Comment by saikrishnarallabandi** [comment]
[Here](https://github.com/festvox/festvox/blob/master/voices/arctic/rms/local/train_phones_tensordash.py) is a script with a sample integration of tensordash. This is example of former case. [Here](https://github.com/festvox/festvox/blob/master/challenges/blizzard2020/v1/local/train_quants_tensordash.py) is an example script of the latter

**Comment by harshitm98** [comment]
Okay. That behaviour is not expected. Give us time, we will try to figure it out and fix it by the next release.

**Comment by CleanPegasus** [comment]
Hey Sai Krishna! Thanks for bringing this issue to light. We have fixed it in the latest version of the tensor-dash package, tensor-dash 1.8.1. Please use this and let us know if you face any more problems.
Thank you!
