### ISSUE TITLE
ValueError: bad marshal data (unknown type code)

### ISSUE THREAD

**Issue by azeem110201** [CleanPegasus/TensorDash#26]
**Describe the bug**
the command 
!python setup.py install  is not running in colab or kaggle notebook and showing some value-error

**To Reproduce**
1. !python setup.py install
2. See error : ValueError: bad marshal data (unknown type code)

**Package**
- Package Version: [eg, v1.6]
- Deep learning framework used: [eg. keras, tensorflow]

**Desktop (please complete the following information):**
 - Browser chrome

**Comment by CleanPegasus** [comment]
Hi! Kindly try using !pip3 install tensor-dash at the moment. We will try to fix this issue in the meantime.
